export default {
  a:require('../img/a.png'),
  aab1: require('../img/aab1.png'),
  aab2: require('../img/aab2.png'),
  activation_head: require('../img/activation_head.png'),
  add: require('../img/add.png'),
  Agent: require('../img/Agent.png'),
  AgentInfo_bg: require('../img/AgentInfo_bg.png'),
  al:require('../img/al.png'),
  b:require('../img/b.png'),
  c:require('../img/c.png'),
  Calculation:require('../img/Calculation.png'),
  candy:require('../img/candy.png'),
  cmy_db:require('../img/cmy_db.png'),
  cmy_gzh:require('../img/cmy_gzh.png'),
  cmy_kydz:require('../img/cmy_kydz.png'),
  cmy_qq:require('../img/cmy_qq.png'),
  cmy_wb:require('../img/cmy_wb.png'),
  cmy_wx:require('../img/cmy_wx.png'),
  cmyhead:require('../img/cmyhead_by.png'),
  copy:require('../img/copy.png'),
  d:require('../img/d.png'),
  details:require('../img/details.png'),
  down_h:require('../img/down_h.png'),
  down:require('../img/down.png'),
  eos: require('../img/eos.png'),
  fav_h: require('../img/fav_h.png'),
  fav: require('../img/fav.png'),
  guide:require('../img/guide.png'),
  home_bg: require('../img/home_bg.png'),
  imvote:require('../img/imvote.png'),
  inb:require('../img/inb.png'),
  integral_bg:require('../img/integral_bg.png'),
  Invitation_vote:require('../img/Invitation_vote.png'),
  line_bg:require('../img/line_bg.png'),
  link:require('../img/link.png'),
  lock:require('../img/lock.png'),
  logo:require('../img/logo1.png'),
  Magnifier:require('../img/Magnifier.png'),
  Magnifier_me:require('../img/Magnifier_me.png'),
  Memory:require('../img/Memory.png'),
  MessagePush:require('../img/MessagePush.png'),
  more:require('../img/more.png'),
  my_community:require('../img/my_community.png'),
  my_help:require('../img/my_help.png'),
  my_recovery:require('../img/my_recovery.png'),
  my_share:require('../img/my_share.png'),
  my_system:require('../img/my_system.png'),
  my_wallet:require('../img/my_wallet.png'),
  nash:require('../img/nash.png'),
  network:require('../img/network.png'),
  phone:require('../img/phone.png'),
  point_empty:require('../img/point_empty.png'),
  point_full:require('../img/point_full.png'),
  privatekey:require('../img/privatekey.png'),
  progressbar_a:require('../img/progressbar_a.png'),
  progressbar_b:require('../img/progressbar_b.png'),
  publickey:require('../img/publickey.png'),
  qr: require('../img/qr.png'),
  qrcode:require('../img/qrcode.png'),
  refresh:require('../img/refresh.png'),
  resources_bj:require('../img/resources_bj.png'),
  resources_f:require('../img/resources_f.png'),
  resources:require('../img/resources.png'),
  reveal_h:require('../img/reveal_h.png'),
  reveal:require('../img/reveal.png'),
  reveal_h_wallet:require('../img/reveal_h_wallet.png'),
  reveal_wallet:require('../img/reveal_wallet.png'),
  scan: require('../img/scan.png'),
  share_banner:require('../img/share_banner.png'),
  shareBg:require('../img/share_bg.png'),
  share_bottom:require('../img/share_bottom.png'),
  share_i:require('../img/share_i.png'),
  share_img:require('../img/share_img.png'),
  share_pyq:require('../img/share_pyq.png'),
  share_qq:require('../img/share_qq.png'),
  share_Size:require('../img/share_Size.png'),
  share_time:require('../img/share_time.png'),
  share_wx:require('../img/share_wx.png'),
  share:require('../img/share.png'),
  shift_to:require('../img/shift_to.png'),
  signed:require('../img/signed.png'),  
  small_bell_h:require('../img/small_bell_h.png'),  
  small_bell:require('../img/small_bell.png'),  
  strip_bg:require('../img/strip_bg.png'),
  tab_1_h: require('../img/tab_1_h.png'),
  tab_1: require('../img/tab_1.png'),
  tab_2_h: require('../img/tab_2_h.png'),
  tab_2: require('../img/tab_2.png'),
  tab_3_h: require('../img/tab_3_h.png'),
  tab_3: require('../img/tab_3.png'),
  tab_4_h: require('../img/tab_4_h.png'),
  tab_4: require('../img/tab_4.png'),
  tab_5_h:require('../img/tab_5_h.png'),
  tab_5:require('../img/tab_5.png'),
  tag:require('../img/tag.png'),
  Tick_h:require('../img/Tick_h.png'),
  Tick:require('../img/Tick.png'),
  transfer:require('../img/transfer.png'),
  trend_cpu:require('../img/trend_cpu.png'),
  turn_out:require('../img/turn_out.png'),
  turnin_head:require('../img/turninhead.png'),
  up_h:require('../img/up_h.png'),
  up:require('../img/up.png'),
  vote_h:require('../img/vote_h.png'),
  vote_node:require('../img/vote_node.png'),
  vote:require('../img/vote.png'),
  votea_bj:require('../img/votea_bj.png'),
  votea:require('../img/votea.png'),
  voteb_bj:require('../img/voteb_bj.png'),
  voteb:require('../img/voteb.png'),
  votec_bj:require('../img/votec_bj.png'),
  votec:require('../img/votec.png'),
  voted_bj:require('../img/voted_bj.png'),
  voted:require('../img/voted.png'),
  wallet_1:require('../img/wallet_1.png'),
  wallet: require('../img/wallet.png'),
  warning:require('../img/warning.png'),
  xin0:require('../img/xin0.png'),
  xin1:require('../img/xin1.png'),
}